# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=8.4.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-8.4.0'
  - '.'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
  args: ['version']

images:
- 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
